"use strict";
var form=document.getElementById("formulario");
form["breg"].addEventListener("click",alerta, false);
function alerta()
    {
    var mensaje;
    var opcion = confirm("Por datos personales se entiende toda información sobre una persona física identificada o identificable (“persona interesada”); una persona física identificable es aquella que puede identificarse, directa o indirectamente, en particular mediante un identificador como un nombre, un número de identificación, datos de ubicación, un identificador en línea o uno o varios elementos específicos característicos de la identidad física, fisiológica, genética, mental, económica, cultural o social de dicha persona física. Esto incluye datos como su nombre real, dirección, número de teléfono y fecha de nacimiento. La información que no pueda vincularse directamente a su identidad real, como sitios web favoritos o número de usuarios de un sitio, no se considera dentro de los datos personales. Por motivos de seguridad, cuando visita nuestras páginas web, nuestros servidores web guardan temporalmente los datos de conexión del computador con el que se conecta, una lista de las páginas web que visita dentro del sitio, la fecha y duración de su visita. La base jurídica del tratamiento de las categorías de datos anteriores es el Art. 6 (1) (a) del Reglamento general de protección de datos (GDPR, por sus siglas en íngles) Europeo. Con dichos fines, en particular para garantizar la seguridad y una configuración de la conexión fluida, tenemos un interés legítimo en el tratamiento de dichos datos.Siempre que haya activado las funciones de geolocalización en el navegador, respectivamente en su sistema operativo utilizaremos dichos datos para ofrecerle servicios basados en su ubicación (por ejemplo, ubicación de la sucursal o el centro de empaquetado más cercanos, etc.). No utilizaremos estos datos con ningún otro fin. Si desactiva esta función, sus datos se eliminarán a su debido tiempo.La base jurídica del tratamiento anterior es el Art. 6 (1) f) del GDPR. Se considera que el tratamiento de los datos de clientes con fines propios de marketing directo se lleva a cabo por un interés legítimo. Usted tiene derecho a oponerse a dicho tratamiento en cualquier momento. Para ejercer su derecho, solo tiene que ponerse en contacto con nosotros a través de los datos de contacto que se indican en Quién es responsable de estos datos. Si se suscribe a uno de nuestros boletines, nos autoriza a utilizar su dirección de correo electrónico con este fin. La base legal para este procesamiento de datos es su consentimiento de conformidad con el Artículo 6 (1) (a) del RGPD. Puede cancelar su suscripción al boletín en cualquier momento haciendo clic en el enlace correspondiente situado en la parte inferior del boletín. También puede revocar...");
    if (opcion == true) {
        mensaje = "Has clickado OK";
	} else {
	    mensaje = "Has clickado Cancelar";
	}
	document.getElementById("ejemplo").innerHTML = mensaje;
    }